add  function to proofreading.sh
tfug/proofreading pull request #10
Opened 2019-05-16 13:47 UTC by chie8842

https://github.com/tfug/proofreading/pull/7#issuecomment-492728149

上記コメントに従ってmarkdownファイルもチェックできるようにしました。

2019-05-16 14:56 UTC, sfujiwara requested changes
markdown の階層が `site/ja/*/*/*.md` じゃなくて `site/ja/*/*.md` のときにコピーじゃなくてディレクトリが作成されちゃってるっぽいですね。
このへんであり得るケースなので直しておいた方が良さそう:
https://github.com/tensorflow/docs/tree/master/site/ja/xla

2019-05-18 08:53 UTC, chie8842 commented
お、すまへん！なおします:bow:

2019-05-18 09:19 UTC, chie8842 commented
直しました。

2019-05-18 16:41 UTC, sfujiwara approved these changes

2019-05-18 16:42 UTC, sfujiwara commented
良さそうなのでマージします〜

2019-05-18 16:42 UTC, merged