handle html file
tfug/proofreading pull request #16
Opened 2019-06-21 08:21 UTC by chie8842

#13 の対応です。
@sfujiwara @ohtaman レビューお願いしたいです。

2019-09-17 17:20 UTC, sfujiwara commented
動作確認するのでマージ少々お待ちをー

2019-09-27 18:19 UTC, sfujiwara requested changes

2019-09-27 18:19 UTC, sfujiwara commented on src/html_converter.py
> +        output = os.path.join(output_dir, os.path.basename(input_file))
拡張子 `.md` に変更せず `.html` のまま保存しちゃっているのでこうかな？

```suggestion
        output_file = '{}.md'.format(os.path.basename(input_file).split('.')[0])
        output = os.path.join(output_dir, output_file)
```

2019-10-21 07:23 UTC, chie8842 commented on src/html_converter.py
> +        output = os.path.join(output_dir, os.path.basename(input_file))
すみません！こちらのコメント見落としていました。。
修正しました:bow:

2019-10-24 20:01 UTC, sfujiwara commented
LGTM!

2019-10-24 20:01 UTC, sfujiwara approved these changes

2019-10-24 20:01 UTC, merged