Feature/diff chie8842
tfug/proofreading pull request #41
Opened 2019-12-01 06:05 UTC by chie8842

@sfujiwara スクリプトですが、なるべく重複部分をなくしたかったので、
わたしがこうしたいな、と思うように少し変えてみました！
どうでしょうか？

修正点：

* d43899b 397363d
  1. bin/run をbin/run-allに、bin/diffをbin/run-diffに名称変更
  2. bin/diffとbin/runで重複する部分を切り出してrunスクリプトとして、runスクリプトからrun-diffもしくはrun-allスクリプトを呼び出すようにする
  3. スクリプトの親子関係がわかりやすいようにヘッダ追加
  4. OUTPUT_FILEは[ここ](https://github.com/tfug/proofreading/blob/master/bin/run#L35)のoutputと表現がかぶるのでLOG_FILEに名称変更し、ファイル名は固定にする
* 2c6c85b  README修正

2019-12-17 16:44 UTC, sfujiwara commented
設計方針とかざっくりコード見た感じは賛成です！
#37 #39 の前にこっちをマージした方が良さそうなので、先にこっち見ますね
細かい動作確認とかはまだなので、少々お待ちを

2019-12-21 07:53 UTC, sfujiwara requested changes
`ash` が明示的に指定されていて Docker を使わずに直接 `./bin/run` を実行した時に動かないので

* Suggestion のような感じで `#!/bin/sh` で指定する
* Docker を使った実行のみサポートする方針にする
  * この場合は `README.md` から "Without Docker" の項目を削除する

のいずれかの対応が必要そうです。
どちらの方針もありだと思うので、好きな方を選んじゃって良いかと。

その他の動作確認は大丈夫そうでした。

2019-12-21 07:53 UTC, sfujiwara commented on bin/run
> +#!/bin/ash
```suggestion
#!/bin/sh
```

2019-12-21 07:53 UTC, sfujiwara commented on bin/run
> +  /bin/ash bin/run-all $@
```suggestion
  ./bin/run-all $@
```

2019-12-21 07:53 UTC, sfujiwara commented on bin/run
> +  /bin/ash bin/run-diff $@
```suggestion
  ./bin/run-diff $@
```

2019-12-21 07:53 UTC, sfujiwara commented on bin/run-all
> +#!/bin/ash
```suggestion
#!/bin/sh
```

2019-12-21 07:53 UTC, sfujiwara commented on bin/run-diff
> +#!/bin/ash
```suggestion
#!/bin/sh
```

2019-12-21 07:54 UTC, sfujiwara commented
メンションをつけ忘れていた
@chie8842 だいぶ遅くなっちゃいましたが、レビューしましたー

2019-12-21 09:00 UTC, chie8842 commented
ありがとうございます！suggestion反映したのと、READMEを少し修正しました🙏

2019-12-22 07:11 UTC, sfujiwara approved these changes
LGTM!

2019-12-22 07:11 UTC, merged

2019-12-22 08:03 UTC, sfujiwara commented
あああ！
これ `feature/diff` の方にマージしていたのかああ！
master にマージしたと思って、ミスって `feature/diff` を消すというやらかしをしてしもうた...